_ocmo:
  parameters:
    env_name:
      type: projected
      value: .Path[-2]
      description: Environment segment from config path
      transformers:
        - upper

environment: "{!env_name}"
