"""AUTO-GENERATED by scripts/generate_facade.py — do not edit."""

from __future__ import annotations

DEFAULT_PAGE_SIZE = 100

PAGINATED: dict[str, tuple[str, str]] = {
    "list_global_audit": ('items', 'count'),
    "list_global_permissions": ('rules', 'count'),
    "list_item_versions": ('versions', 'versions_count'),
    "list_locks": ('locks', 'count'),
    "list_namespace_audit": ('items', 'count'),
    "list_namespaces": ('items', 'count'),
    "namespace_audit_timeline": ('items', 'count'),
    "navigate_path": ('children', 'children_count'),
    "navigate_root": ('children', 'children_count'),
    "search_path": ('items', 'count'),
    "search_root": ('items', 'count'),
}

DOCUMENT_BODY_OPS = frozenset(
    {
        "create_config",
        "create_resolver",
        "create_secret",
        "create_template",
        "resolve_draft_config",
        "update_config",
        "update_resolver",
        "update_secret",
        "update_template",
    }
)

BODY_PAYLOADS: dict[str, tuple[str, str, list[str]]] = {
    "can_i": ('ocmo._generated.models.can_i_request_schema', 'CanIRequestSchema', ['operations', 'namespace', 'resource']),
    "copy_item": ('ocmo._generated.models.location_payload', 'LocationPayload', ['target_path']),
    "create_global_permission": ('ocmo._generated.models.global_permission_rule_payload', 'GlobalPermissionRulePayload', ['namespace', 'id', 'description', 'read', 'write', 'delete', 'audit']),
    "create_lock": ('ocmo._generated.models.lock_payload', 'LockPayload', ['reason', 'expires_at']),
    "create_namespace": ('ocmo._generated.models.namespace_create_schema', 'NamespaceCreateSchema', ['name', 'description']),
    "describe_item": ('ocmo._generated.models.describe_payload', 'DescribePayload', ['description']),
    "move_global_permission": ('ocmo._generated.models.global_permission_rule_move_payload', 'GlobalPermissionRuleMovePayload', ['position']),
    "move_item": ('ocmo._generated.models.location_payload', 'LocationPayload', ['target_path']),
    "replace_lock": ('ocmo._generated.models.lock_payload', 'LockPayload', ['reason', 'expires_at']),
    "rotate_resolver_token": ('ocmo._generated.models.resolver_rotate_token_payload', 'ResolverRotateTokenPayload', ['token_number']),
    "set_tag": ('ocmo._generated.models.tag_payload', 'TagPayload', ['tag', 'version']),
    "update_global_permission": ('ocmo._generated.models.global_permission_rule_payload', 'GlobalPermissionRulePayload', ['namespace', 'id', 'description', 'read', 'write', 'delete', 'audit']),
    "update_namespace": ('ocmo._generated.models.namespace_patch_schema', 'NamespacePatchSchema', ['name', 'description', 'permissions_tag', 'webhooks_tag', 'git_sync_tag']),
}
