"""AUTO-GENERATED by scripts/generate_facade.py — do not edit."""

from __future__ import annotations

from typing import Any

from ocmo._facade_runtime import execute_async, execute_sync
from ocmo._generated.types import UNSET

import ocmo._generated.api.audit.get_global_audit_event as _op_get_global_audit_event
import ocmo._generated.api.audit.get_namespace_audit_event as _op_get_namespace_audit_event
import ocmo._generated.api.audit.list_global_audit as _op_list_global_audit
import ocmo._generated.api.audit.list_namespace_audit as _op_list_namespace_audit
import ocmo._generated.api.audit.namespace_audit_resolve_series as _op_namespace_audit_resolve_series
import ocmo._generated.api.audit.namespace_audit_timeline as _op_namespace_audit_timeline
import ocmo._generated.api.auth.can_i as _op_can_i
import ocmo._generated.api.auth.whoami as _op_whoami
import ocmo._generated.api.config.create_config as _op_create_config
import ocmo._generated.api.config.get_config_data_schema as _op_get_config_data_schema
import ocmo._generated.api.config.get_config_metadata_schema as _op_get_config_metadata_schema
import ocmo._generated.api.config.update_config as _op_update_config
import ocmo._generated.api.global_permissions.create_global_permission as _op_create_global_permission
import ocmo._generated.api.global_permissions.delete_global_permission as _op_delete_global_permission
import ocmo._generated.api.global_permissions.get_global_permission as _op_get_global_permission
import ocmo._generated.api.global_permissions.list_global_permissions as _op_list_global_permissions
import ocmo._generated.api.global_permissions.move_global_permission as _op_move_global_permission
import ocmo._generated.api.global_permissions.update_global_permission as _op_update_global_permission
import ocmo._generated.api.lock.create_lock as _op_create_lock
import ocmo._generated.api.lock.delete_lock as _op_delete_lock
import ocmo._generated.api.lock.get_lock as _op_get_lock
import ocmo._generated.api.lock.list_locks as _op_list_locks
import ocmo._generated.api.lock.replace_lock as _op_replace_lock
import ocmo._generated.api.namespace.create_namespace as _op_create_namespace
import ocmo._generated.api.namespace.delete_namespace as _op_delete_namespace
import ocmo._generated.api.namespace.list_namespaces as _op_list_namespaces
import ocmo._generated.api.namespace.show_namespace as _op_show_namespace
import ocmo._generated.api.namespace.update_namespace as _op_update_namespace
import ocmo._generated.api.propagation.propagate_config as _op_propagate_config
import ocmo._generated.api.resolve.list_cast_formats as _op_list_cast_formats
import ocmo._generated.api.resolve.resolve_draft_config as _op_resolve_draft_config
import ocmo._generated.api.resolve.resolve_parameters as _op_resolve_parameters
import ocmo._generated.api.resolver.create_resolver as _op_create_resolver
import ocmo._generated.api.resolver.get_resolver_configuration_schema as _op_get_resolver_configuration_schema
import ocmo._generated.api.resolver.rotate_resolver_token as _op_rotate_resolver_token
import ocmo._generated.api.resolver.update_resolver as _op_update_resolver
import ocmo._generated.api.secret.create_secret as _op_create_secret
import ocmo._generated.api.secret.update_secret as _op_update_secret
import ocmo._generated.api.system.health as _op_health
import ocmo._generated.api.system.version as _op_version
import ocmo._generated.api.template.create_template as _op_create_template
import ocmo._generated.api.template.update_template as _op_update_template
import ocmo._generated.api.tree.copy_item as _op_copy_item
import ocmo._generated.api.tree.delete_item as _op_delete_item
import ocmo._generated.api.tree.describe_item as _op_describe_item
import ocmo._generated.api.tree.diff_item as _op_diff_item
import ocmo._generated.api.tree.get_item as _op_get_item
import ocmo._generated.api.tree.list_item_versions as _op_list_item_versions
import ocmo._generated.api.tree.move_item as _op_move_item
import ocmo._generated.api.tree.navigate_path as _op_navigate_path
import ocmo._generated.api.tree.navigate_root as _op_navigate_root
import ocmo._generated.api.tree.search_path as _op_search_path
import ocmo._generated.api.tree.search_root as _op_search_root
import ocmo._generated.api.tree.set_tag as _op_set_tag

class _ClientFacadeMixin:
    def can_i(self, *, operations: Any = UNSET, namespace: Any = UNSET, resource: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``can_i``."""

        return execute_sync(
            "can_i",
            _op_can_i.sync_detailed,
            operations=operations, namespace=namespace, resource=resource, body=body,
            client=self._api,
        )

    def create_global_permission(self, *, namespace: Any = UNSET, id: Any = UNSET, description: Any = UNSET, read: Any = UNSET, write: Any = UNSET, delete: Any = UNSET, audit: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_global_permission``."""

        return execute_sync(
            "create_global_permission",
            _op_create_global_permission.sync_detailed,
            namespace=namespace, id=id, description=description, read=read, write=write, delete=delete, audit=audit, body=body,
            client=self._api,
        )

    def create_namespace(self, *, name: Any = UNSET, description: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_namespace``."""

        return execute_sync(
            "create_namespace",
            _op_create_namespace.sync_detailed,
            name=name, description=description, body=body,
            client=self._api,
        )

    def delete_global_permission(self, rule_id: Any):
        """OpenAPI operation ``delete_global_permission``."""

        return execute_sync(
            "delete_global_permission",
            _op_delete_global_permission.sync_detailed,
            rule_id,
            client=self._api,
        )

    def delete_namespace(self, namespace: Any):
        """OpenAPI operation ``delete_namespace``."""

        return execute_sync(
            "delete_namespace",
            _op_delete_namespace.sync_detailed,
            namespace,
            client=self._api,
        )

    def get_config_metadata_schema(self):
        """OpenAPI operation ``get_config_metadata_schema``."""

        return execute_sync(
            "get_config_metadata_schema",
            _op_get_config_metadata_schema.sync_detailed,
            client=self._api,
        )

    def get_global_audit_event(self, event_id: Any):
        """OpenAPI operation ``get_global_audit_event``."""

        return execute_sync(
            "get_global_audit_event",
            _op_get_global_audit_event.sync_detailed,
            event_id,
            client=self._api,
        )

    def get_global_permission(self, rule_id: Any):
        """OpenAPI operation ``get_global_permission``."""

        return execute_sync(
            "get_global_permission",
            _op_get_global_permission.sync_detailed,
            rule_id,
            client=self._api,
        )

    def get_resolver_configuration_schema(self):
        """OpenAPI operation ``get_resolver_configuration_schema``."""

        return execute_sync(
            "get_resolver_configuration_schema",
            _op_get_resolver_configuration_schema.sync_detailed,
            client=self._api,
        )

    def health(self):
        """OpenAPI operation ``health``."""

        return execute_sync(
            "health",
            _op_health.sync_detailed,
            client=self._api,
        )

    def list_cast_formats(self):
        """OpenAPI operation ``list_cast_formats``."""

        return execute_sync(
            "list_cast_formats",
            _op_list_cast_formats.sync_detailed,
            client=self._api,
        )

    def list_global_audit(self, *, auth_id: Any = UNSET, auth_email: Any = UNSET, auth_type: Any = UNSET, object_type: Any = UNSET, object_id: Any = UNSET, http_method: Any = UNSET, api_endpoint: Any = UNSET, permission_ok: Any = UNSET, resolve_type: Any = UNSET, from_cache: Any = UNSET, event_kind: Any = UNSET, category: Any = UNSET, parent_event_id: Any = UNSET, client_ip: Any = UNSET, user_agent: Any = UNSET, token_number: Any = UNSET, object_version: Any = UNSET, operation: Any = UNSET, subresource_type: Any = UNSET, subresource: Any = UNSET, event_id: Any = UNSET, error: Any = UNSET, namespace: Any = UNSET, search: Any = UNSET, from_: Any = UNSET, to: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_global_audit``."""

        return execute_sync(
            "list_global_audit",
            _op_list_global_audit.sync_detailed,
            auth_id=auth_id, auth_email=auth_email, auth_type=auth_type, object_type=object_type, object_id=object_id, http_method=http_method, api_endpoint=api_endpoint, permission_ok=permission_ok, resolve_type=resolve_type, from_cache=from_cache, event_kind=event_kind, category=category, parent_event_id=parent_event_id, client_ip=client_ip, user_agent=user_agent, token_number=token_number, object_version=object_version, operation=operation, subresource_type=subresource_type, subresource=subresource, event_id=event_id, error=error, namespace=namespace, search=search, from_=from_, to=to, limit=limit, offset=offset,
            client=self._api,
        )

    def list_global_permissions(self, *, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_global_permissions``."""

        return execute_sync(
            "list_global_permissions",
            _op_list_global_permissions.sync_detailed,
            limit=limit, offset=offset,
            client=self._api,
        )

    def list_namespaces(self, *, name_filter: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_namespaces``."""

        return execute_sync(
            "list_namespaces",
            _op_list_namespaces.sync_detailed,
            name_filter=name_filter, limit=limit, offset=offset,
            client=self._api,
        )

    def move_global_permission(self, rule_id: Any, *, position: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``move_global_permission``."""

        return execute_sync(
            "move_global_permission",
            _op_move_global_permission.sync_detailed,
            rule_id, position=position, body=body,
            client=self._api,
        )

    def show_namespace(self, namespace: Any):
        """OpenAPI operation ``show_namespace``."""

        return execute_sync(
            "show_namespace",
            _op_show_namespace.sync_detailed,
            namespace,
            client=self._api,
        )

    def update_global_permission(self, rule_id: Any, *, namespace: Any = UNSET, id: Any = UNSET, description: Any = UNSET, read: Any = UNSET, write: Any = UNSET, delete: Any = UNSET, audit: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_global_permission``."""

        return execute_sync(
            "update_global_permission",
            _op_update_global_permission.sync_detailed,
            rule_id, namespace=namespace, id=id, description=description, read=read, write=write, delete=delete, audit=audit, body=body,
            client=self._api,
        )

    def update_namespace(self, namespace: Any, *, name: Any = UNSET, description: Any = UNSET, permissions_tag: Any = UNSET, webhooks_tag: Any = UNSET, git_sync_tag: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_namespace``."""

        return execute_sync(
            "update_namespace",
            _op_update_namespace.sync_detailed,
            namespace, name=name, description=description, permissions_tag=permissions_tag, webhooks_tag=webhooks_tag, git_sync_tag=git_sync_tag, body=body,
            client=self._api,
        )

    def version(self, *, notice: Any = UNSET):
        """OpenAPI operation ``version``."""

        return execute_sync(
            "version",
            _op_version.sync_detailed,
            notice=notice,
            client=self._api,
        )

    def whoami(self):
        """OpenAPI operation ``whoami``."""

        return execute_sync(
            "whoami",
            _op_whoami.sync_detailed,
            client=self._api,
        )


class _AsyncClientFacadeMixin:
    async def can_i(self, *, operations: Any = UNSET, namespace: Any = UNSET, resource: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``can_i``."""

        return await execute_async(
            "can_i",
            _op_can_i.asyncio_detailed,
            operations=operations, namespace=namespace, resource=resource, body=body,
            client=self._api,
        )

    async def create_global_permission(self, *, namespace: Any = UNSET, id: Any = UNSET, description: Any = UNSET, read: Any = UNSET, write: Any = UNSET, delete: Any = UNSET, audit: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_global_permission``."""

        return await execute_async(
            "create_global_permission",
            _op_create_global_permission.asyncio_detailed,
            namespace=namespace, id=id, description=description, read=read, write=write, delete=delete, audit=audit, body=body,
            client=self._api,
        )

    async def create_namespace(self, *, name: Any = UNSET, description: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_namespace``."""

        return await execute_async(
            "create_namespace",
            _op_create_namespace.asyncio_detailed,
            name=name, description=description, body=body,
            client=self._api,
        )

    async def delete_global_permission(self, rule_id: Any):
        """OpenAPI operation ``delete_global_permission``."""

        return await execute_async(
            "delete_global_permission",
            _op_delete_global_permission.asyncio_detailed,
            rule_id,
            client=self._api,
        )

    async def delete_namespace(self, namespace: Any):
        """OpenAPI operation ``delete_namespace``."""

        return await execute_async(
            "delete_namespace",
            _op_delete_namespace.asyncio_detailed,
            namespace,
            client=self._api,
        )

    async def get_config_metadata_schema(self):
        """OpenAPI operation ``get_config_metadata_schema``."""

        return await execute_async(
            "get_config_metadata_schema",
            _op_get_config_metadata_schema.asyncio_detailed,
            client=self._api,
        )

    async def get_global_audit_event(self, event_id: Any):
        """OpenAPI operation ``get_global_audit_event``."""

        return await execute_async(
            "get_global_audit_event",
            _op_get_global_audit_event.asyncio_detailed,
            event_id,
            client=self._api,
        )

    async def get_global_permission(self, rule_id: Any):
        """OpenAPI operation ``get_global_permission``."""

        return await execute_async(
            "get_global_permission",
            _op_get_global_permission.asyncio_detailed,
            rule_id,
            client=self._api,
        )

    async def get_resolver_configuration_schema(self):
        """OpenAPI operation ``get_resolver_configuration_schema``."""

        return await execute_async(
            "get_resolver_configuration_schema",
            _op_get_resolver_configuration_schema.asyncio_detailed,
            client=self._api,
        )

    async def health(self):
        """OpenAPI operation ``health``."""

        return await execute_async(
            "health",
            _op_health.asyncio_detailed,
            client=self._api,
        )

    async def list_cast_formats(self):
        """OpenAPI operation ``list_cast_formats``."""

        return await execute_async(
            "list_cast_formats",
            _op_list_cast_formats.asyncio_detailed,
            client=self._api,
        )

    async def list_global_audit(self, *, auth_id: Any = UNSET, auth_email: Any = UNSET, auth_type: Any = UNSET, object_type: Any = UNSET, object_id: Any = UNSET, http_method: Any = UNSET, api_endpoint: Any = UNSET, permission_ok: Any = UNSET, resolve_type: Any = UNSET, from_cache: Any = UNSET, event_kind: Any = UNSET, category: Any = UNSET, parent_event_id: Any = UNSET, client_ip: Any = UNSET, user_agent: Any = UNSET, token_number: Any = UNSET, object_version: Any = UNSET, operation: Any = UNSET, subresource_type: Any = UNSET, subresource: Any = UNSET, event_id: Any = UNSET, error: Any = UNSET, namespace: Any = UNSET, search: Any = UNSET, from_: Any = UNSET, to: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_global_audit``."""

        return await execute_async(
            "list_global_audit",
            _op_list_global_audit.asyncio_detailed,
            auth_id=auth_id, auth_email=auth_email, auth_type=auth_type, object_type=object_type, object_id=object_id, http_method=http_method, api_endpoint=api_endpoint, permission_ok=permission_ok, resolve_type=resolve_type, from_cache=from_cache, event_kind=event_kind, category=category, parent_event_id=parent_event_id, client_ip=client_ip, user_agent=user_agent, token_number=token_number, object_version=object_version, operation=operation, subresource_type=subresource_type, subresource=subresource, event_id=event_id, error=error, namespace=namespace, search=search, from_=from_, to=to, limit=limit, offset=offset,
            client=self._api,
        )

    async def list_global_permissions(self, *, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_global_permissions``."""

        return await execute_async(
            "list_global_permissions",
            _op_list_global_permissions.asyncio_detailed,
            limit=limit, offset=offset,
            client=self._api,
        )

    async def list_namespaces(self, *, name_filter: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_namespaces``."""

        return await execute_async(
            "list_namespaces",
            _op_list_namespaces.asyncio_detailed,
            name_filter=name_filter, limit=limit, offset=offset,
            client=self._api,
        )

    async def move_global_permission(self, rule_id: Any, *, position: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``move_global_permission``."""

        return await execute_async(
            "move_global_permission",
            _op_move_global_permission.asyncio_detailed,
            rule_id, position=position, body=body,
            client=self._api,
        )

    async def show_namespace(self, namespace: Any):
        """OpenAPI operation ``show_namespace``."""

        return await execute_async(
            "show_namespace",
            _op_show_namespace.asyncio_detailed,
            namespace,
            client=self._api,
        )

    async def update_global_permission(self, rule_id: Any, *, namespace: Any = UNSET, id: Any = UNSET, description: Any = UNSET, read: Any = UNSET, write: Any = UNSET, delete: Any = UNSET, audit: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_global_permission``."""

        return await execute_async(
            "update_global_permission",
            _op_update_global_permission.asyncio_detailed,
            rule_id, namespace=namespace, id=id, description=description, read=read, write=write, delete=delete, audit=audit, body=body,
            client=self._api,
        )

    async def update_namespace(self, namespace: Any, *, name: Any = UNSET, description: Any = UNSET, permissions_tag: Any = UNSET, webhooks_tag: Any = UNSET, git_sync_tag: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_namespace``."""

        return await execute_async(
            "update_namespace",
            _op_update_namespace.asyncio_detailed,
            namespace, name=name, description=description, permissions_tag=permissions_tag, webhooks_tag=webhooks_tag, git_sync_tag=git_sync_tag, body=body,
            client=self._api,
        )

    async def version(self, *, notice: Any = UNSET):
        """OpenAPI operation ``version``."""

        return await execute_async(
            "version",
            _op_version.asyncio_detailed,
            notice=notice,
            client=self._api,
        )

    async def whoami(self):
        """OpenAPI operation ``whoami``."""

        return await execute_async(
            "whoami",
            _op_whoami.asyncio_detailed,
            client=self._api,
        )


class _NamespaceFacadeMixin:
    def copy_item(self, path: Any, *, tag_to_copy: Any = UNSET, target_path: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``copy_item``."""

        return execute_sync(
            "copy_item",
            _op_copy_item.sync_detailed,
            self._namespace, path, tag_to_copy=tag_to_copy, target_path=target_path, body=body,
            client=self._api,
        )

    def create_config(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_config``."""

        return execute_sync(
            "create_config",
            _op_create_config.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    def create_lock(self, path: Any, *, reason: Any = UNSET, expires_at: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_lock``."""

        return execute_sync(
            "create_lock",
            _op_create_lock.sync_detailed,
            self._namespace, path, reason=reason, expires_at=expires_at, body=body,
            client=self._api,
        )

    def create_resolver(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_resolver``."""

        return execute_sync(
            "create_resolver",
            _op_create_resolver.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    def create_secret(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_secret``."""

        return execute_sync(
            "create_secret",
            _op_create_secret.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    def create_template(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_template``."""

        return execute_sync(
            "create_template",
            _op_create_template.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    def delete_item(self, path: Any, *, preview: Any = UNSET, version: Any = UNSET):
        """OpenAPI operation ``delete_item``."""

        return execute_sync(
            "delete_item",
            _op_delete_item.sync_detailed,
            self._namespace, path, preview=preview, version=version,
            client=self._api,
        )

    def delete_lock(self, path: Any):
        """OpenAPI operation ``delete_lock``."""

        return execute_sync(
            "delete_lock",
            _op_delete_lock.sync_detailed,
            self._namespace, path,
            client=self._api,
        )

    def describe_item(self, path: Any, *, description: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``describe_item``."""

        return execute_sync(
            "describe_item",
            _op_describe_item.sync_detailed,
            self._namespace, path, description=description, body=body,
            client=self._api,
        )

    def diff_item(self, path: Any, *, from_: Any = UNSET, to: Any = UNSET, to_path: Any = UNSET, reveal: Any = UNSET):
        """OpenAPI operation ``diff_item``."""

        return execute_sync(
            "diff_item",
            _op_diff_item.sync_detailed,
            self._namespace, path, from_=from_, to=to, to_path=to_path, reveal=reveal,
            client=self._api,
        )

    def get_config_data_schema(self, path: Any, *, version: Any = UNSET):
        """OpenAPI operation ``get_config_data_schema``."""

        return execute_sync(
            "get_config_data_schema",
            _op_get_config_data_schema.sync_detailed,
            self._namespace, path, version=version,
            client=self._api,
        )

    def get_item(self, path: Any, *, version: Any = UNSET, reveal: Any = UNSET):
        """OpenAPI operation ``get_item``."""

        return execute_sync(
            "get_item",
            _op_get_item.sync_detailed,
            self._namespace, path, version=version, reveal=reveal,
            client=self._api,
        )

    def get_lock(self, path: Any):
        """OpenAPI operation ``get_lock``."""

        return execute_sync(
            "get_lock",
            _op_get_lock.sync_detailed,
            self._namespace, path,
            client=self._api,
        )

    def get_namespace_audit_event(self, event_id: Any):
        """OpenAPI operation ``get_namespace_audit_event``."""

        return execute_sync(
            "get_namespace_audit_event",
            _op_get_namespace_audit_event.sync_detailed,
            self._namespace, event_id,
            client=self._api,
        )

    def list_item_versions(self, path: Any, *, limit: Any = UNSET, offset: Any = UNSET, q: Any = UNSET, tagged_only: Any = UNSET):
        """OpenAPI operation ``list_item_versions``."""

        return execute_sync(
            "list_item_versions",
            _op_list_item_versions.sync_detailed,
            self._namespace, path, limit=limit, offset=offset, q=q, tagged_only=tagged_only,
            client=self._api,
        )

    def list_locks(self, *, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_locks``."""

        return execute_sync(
            "list_locks",
            _op_list_locks.sync_detailed,
            self._namespace, limit=limit, offset=offset,
            client=self._api,
        )

    def list_namespace_audit(self, *, auth_id: Any = UNSET, auth_email: Any = UNSET, auth_type: Any = UNSET, object_type: Any = UNSET, object_id: Any = UNSET, http_method: Any = UNSET, api_endpoint: Any = UNSET, permission_ok: Any = UNSET, resolve_type: Any = UNSET, from_cache: Any = UNSET, event_kind: Any = UNSET, category: Any = UNSET, parent_event_id: Any = UNSET, client_ip: Any = UNSET, user_agent: Any = UNSET, token_number: Any = UNSET, object_version: Any = UNSET, operation: Any = UNSET, subresource_type: Any = UNSET, subresource: Any = UNSET, event_id: Any = UNSET, error: Any = UNSET, search: Any = UNSET, from_: Any = UNSET, to: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_namespace_audit``."""

        return execute_sync(
            "list_namespace_audit",
            _op_list_namespace_audit.sync_detailed,
            self._namespace, auth_id=auth_id, auth_email=auth_email, auth_type=auth_type, object_type=object_type, object_id=object_id, http_method=http_method, api_endpoint=api_endpoint, permission_ok=permission_ok, resolve_type=resolve_type, from_cache=from_cache, event_kind=event_kind, category=category, parent_event_id=parent_event_id, client_ip=client_ip, user_agent=user_agent, token_number=token_number, object_version=object_version, operation=operation, subresource_type=subresource_type, subresource=subresource, event_id=event_id, error=error, search=search, from_=from_, to=to, limit=limit, offset=offset,
            client=self._api,
        )

    def move_item(self, path: Any, *, target_path: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``move_item``."""

        return execute_sync(
            "move_item",
            _op_move_item.sync_detailed,
            self._namespace, path, target_path=target_path, body=body,
            client=self._api,
        )

    def namespace_audit_resolve_series(self, *, object_id: Any = UNSET, object_type: Any = UNSET, from_: Any = UNSET, to: Any = UNSET, bucket_seconds: Any = UNSET):
        """OpenAPI operation ``namespace_audit_resolve_series``."""

        return execute_sync(
            "namespace_audit_resolve_series",
            _op_namespace_audit_resolve_series.sync_detailed,
            self._namespace, object_id=object_id, object_type=object_type, from_=from_, to=to, bucket_seconds=bucket_seconds,
            client=self._api,
        )

    def namespace_audit_timeline(self, *, object_id: Any = UNSET, object_type: Any = UNSET, search: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``namespace_audit_timeline``."""

        return execute_sync(
            "namespace_audit_timeline",
            _op_namespace_audit_timeline.sync_detailed,
            self._namespace, object_id=object_id, object_type=object_type, search=search, limit=limit, offset=offset,
            client=self._api,
        )

    def navigate_path(self, path: Any, *, recursive: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``navigate_path``."""

        return execute_sync(
            "navigate_path",
            _op_navigate_path.sync_detailed,
            self._namespace, path, recursive=recursive, limit=limit, offset=offset,
            client=self._api,
        )

    def navigate_root(self, *, recursive: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``navigate_root``."""

        return execute_sync(
            "navigate_root",
            _op_navigate_root.sync_detailed,
            self._namespace, recursive=recursive, limit=limit, offset=offset,
            client=self._api,
        )

    def propagate_config(self, path: Any, *, version: Any = UNSET):
        """OpenAPI operation ``propagate_config``."""

        return execute_sync(
            "propagate_config",
            _op_propagate_config.sync_detailed,
            self._namespace, path, version=version,
            client=self._api,
        )

    def replace_lock(self, path: Any, *, reason: Any = UNSET, expires_at: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``replace_lock``."""

        return execute_sync(
            "replace_lock",
            _op_replace_lock.sync_detailed,
            self._namespace, path, reason=reason, expires_at=expires_at, body=body,
            client=self._api,
        )

    def resolve_draft_config(self, path: Any, *, cast: Any = UNSET, trace_only: Any = UNSET, no_creds: Any = UNSET, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``resolve_draft_config``."""

        return execute_sync(
            "resolve_draft_config",
            _op_resolve_draft_config.sync_detailed,
            self._namespace, path, cast=cast, trace_only=trace_only, no_creds=no_creds, content=content, body=body,
            client=self._api,
        )

    def resolve_parameters(self, path: Any, *, version: Any = UNSET, no_creds: Any = UNSET):
        """OpenAPI operation ``resolve_parameters``."""

        return execute_sync(
            "resolve_parameters",
            _op_resolve_parameters.sync_detailed,
            self._namespace, path, version=version, no_creds=no_creds,
            client=self._api,
        )

    def rotate_resolver_token(self, path: Any, *, token_number: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``rotate_resolver_token``."""

        return execute_sync(
            "rotate_resolver_token",
            _op_rotate_resolver_token.sync_detailed,
            self._namespace, path, token_number=token_number, body=body,
            client=self._api,
        )

    def search_path(self, path: Any, *, q: Any = UNSET, types: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``search_path``."""

        return execute_sync(
            "search_path",
            _op_search_path.sync_detailed,
            self._namespace, path, q=q, types=types, limit=limit, offset=offset,
            client=self._api,
        )

    def search_root(self, *, q: Any = UNSET, types: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``search_root``."""

        return execute_sync(
            "search_root",
            _op_search_root.sync_detailed,
            self._namespace, q=q, types=types, limit=limit, offset=offset,
            client=self._api,
        )

    def set_tag(self, path: Any, *, tag: Any = UNSET, version: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``set_tag``."""

        return execute_sync(
            "set_tag",
            _op_set_tag.sync_detailed,
            self._namespace, path, tag=tag, version=version, body=body,
            client=self._api,
        )

    def update_config(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_config``."""

        return execute_sync(
            "update_config",
            _op_update_config.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    def update_resolver(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_resolver``."""

        return execute_sync(
            "update_resolver",
            _op_update_resolver.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    def update_secret(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_secret``."""

        return execute_sync(
            "update_secret",
            _op_update_secret.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    def update_template(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_template``."""

        return execute_sync(
            "update_template",
            _op_update_template.sync_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )


class _AsyncNamespaceFacadeMixin:
    async def copy_item(self, path: Any, *, tag_to_copy: Any = UNSET, target_path: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``copy_item``."""

        return await execute_async(
            "copy_item",
            _op_copy_item.asyncio_detailed,
            self._namespace, path, tag_to_copy=tag_to_copy, target_path=target_path, body=body,
            client=self._api,
        )

    async def create_config(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_config``."""

        return await execute_async(
            "create_config",
            _op_create_config.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    async def create_lock(self, path: Any, *, reason: Any = UNSET, expires_at: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_lock``."""

        return await execute_async(
            "create_lock",
            _op_create_lock.asyncio_detailed,
            self._namespace, path, reason=reason, expires_at=expires_at, body=body,
            client=self._api,
        )

    async def create_resolver(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_resolver``."""

        return await execute_async(
            "create_resolver",
            _op_create_resolver.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    async def create_secret(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_secret``."""

        return await execute_async(
            "create_secret",
            _op_create_secret.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    async def create_template(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``create_template``."""

        return await execute_async(
            "create_template",
            _op_create_template.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    async def delete_item(self, path: Any, *, preview: Any = UNSET, version: Any = UNSET):
        """OpenAPI operation ``delete_item``."""

        return await execute_async(
            "delete_item",
            _op_delete_item.asyncio_detailed,
            self._namespace, path, preview=preview, version=version,
            client=self._api,
        )

    async def delete_lock(self, path: Any):
        """OpenAPI operation ``delete_lock``."""

        return await execute_async(
            "delete_lock",
            _op_delete_lock.asyncio_detailed,
            self._namespace, path,
            client=self._api,
        )

    async def describe_item(self, path: Any, *, description: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``describe_item``."""

        return await execute_async(
            "describe_item",
            _op_describe_item.asyncio_detailed,
            self._namespace, path, description=description, body=body,
            client=self._api,
        )

    async def diff_item(self, path: Any, *, from_: Any = UNSET, to: Any = UNSET, to_path: Any = UNSET, reveal: Any = UNSET):
        """OpenAPI operation ``diff_item``."""

        return await execute_async(
            "diff_item",
            _op_diff_item.asyncio_detailed,
            self._namespace, path, from_=from_, to=to, to_path=to_path, reveal=reveal,
            client=self._api,
        )

    async def get_config_data_schema(self, path: Any, *, version: Any = UNSET):
        """OpenAPI operation ``get_config_data_schema``."""

        return await execute_async(
            "get_config_data_schema",
            _op_get_config_data_schema.asyncio_detailed,
            self._namespace, path, version=version,
            client=self._api,
        )

    async def get_item(self, path: Any, *, version: Any = UNSET, reveal: Any = UNSET):
        """OpenAPI operation ``get_item``."""

        return await execute_async(
            "get_item",
            _op_get_item.asyncio_detailed,
            self._namespace, path, version=version, reveal=reveal,
            client=self._api,
        )

    async def get_lock(self, path: Any):
        """OpenAPI operation ``get_lock``."""

        return await execute_async(
            "get_lock",
            _op_get_lock.asyncio_detailed,
            self._namespace, path,
            client=self._api,
        )

    async def get_namespace_audit_event(self, event_id: Any):
        """OpenAPI operation ``get_namespace_audit_event``."""

        return await execute_async(
            "get_namespace_audit_event",
            _op_get_namespace_audit_event.asyncio_detailed,
            self._namespace, event_id,
            client=self._api,
        )

    async def list_item_versions(self, path: Any, *, limit: Any = UNSET, offset: Any = UNSET, q: Any = UNSET, tagged_only: Any = UNSET):
        """OpenAPI operation ``list_item_versions``."""

        return await execute_async(
            "list_item_versions",
            _op_list_item_versions.asyncio_detailed,
            self._namespace, path, limit=limit, offset=offset, q=q, tagged_only=tagged_only,
            client=self._api,
        )

    async def list_locks(self, *, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_locks``."""

        return await execute_async(
            "list_locks",
            _op_list_locks.asyncio_detailed,
            self._namespace, limit=limit, offset=offset,
            client=self._api,
        )

    async def list_namespace_audit(self, *, auth_id: Any = UNSET, auth_email: Any = UNSET, auth_type: Any = UNSET, object_type: Any = UNSET, object_id: Any = UNSET, http_method: Any = UNSET, api_endpoint: Any = UNSET, permission_ok: Any = UNSET, resolve_type: Any = UNSET, from_cache: Any = UNSET, event_kind: Any = UNSET, category: Any = UNSET, parent_event_id: Any = UNSET, client_ip: Any = UNSET, user_agent: Any = UNSET, token_number: Any = UNSET, object_version: Any = UNSET, operation: Any = UNSET, subresource_type: Any = UNSET, subresource: Any = UNSET, event_id: Any = UNSET, error: Any = UNSET, search: Any = UNSET, from_: Any = UNSET, to: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``list_namespace_audit``."""

        return await execute_async(
            "list_namespace_audit",
            _op_list_namespace_audit.asyncio_detailed,
            self._namespace, auth_id=auth_id, auth_email=auth_email, auth_type=auth_type, object_type=object_type, object_id=object_id, http_method=http_method, api_endpoint=api_endpoint, permission_ok=permission_ok, resolve_type=resolve_type, from_cache=from_cache, event_kind=event_kind, category=category, parent_event_id=parent_event_id, client_ip=client_ip, user_agent=user_agent, token_number=token_number, object_version=object_version, operation=operation, subresource_type=subresource_type, subresource=subresource, event_id=event_id, error=error, search=search, from_=from_, to=to, limit=limit, offset=offset,
            client=self._api,
        )

    async def move_item(self, path: Any, *, target_path: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``move_item``."""

        return await execute_async(
            "move_item",
            _op_move_item.asyncio_detailed,
            self._namespace, path, target_path=target_path, body=body,
            client=self._api,
        )

    async def namespace_audit_resolve_series(self, *, object_id: Any = UNSET, object_type: Any = UNSET, from_: Any = UNSET, to: Any = UNSET, bucket_seconds: Any = UNSET):
        """OpenAPI operation ``namespace_audit_resolve_series``."""

        return await execute_async(
            "namespace_audit_resolve_series",
            _op_namespace_audit_resolve_series.asyncio_detailed,
            self._namespace, object_id=object_id, object_type=object_type, from_=from_, to=to, bucket_seconds=bucket_seconds,
            client=self._api,
        )

    async def namespace_audit_timeline(self, *, object_id: Any = UNSET, object_type: Any = UNSET, search: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``namespace_audit_timeline``."""

        return await execute_async(
            "namespace_audit_timeline",
            _op_namespace_audit_timeline.asyncio_detailed,
            self._namespace, object_id=object_id, object_type=object_type, search=search, limit=limit, offset=offset,
            client=self._api,
        )

    async def navigate_path(self, path: Any, *, recursive: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``navigate_path``."""

        return await execute_async(
            "navigate_path",
            _op_navigate_path.asyncio_detailed,
            self._namespace, path, recursive=recursive, limit=limit, offset=offset,
            client=self._api,
        )

    async def navigate_root(self, *, recursive: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``navigate_root``."""

        return await execute_async(
            "navigate_root",
            _op_navigate_root.asyncio_detailed,
            self._namespace, recursive=recursive, limit=limit, offset=offset,
            client=self._api,
        )

    async def propagate_config(self, path: Any, *, version: Any = UNSET):
        """OpenAPI operation ``propagate_config``."""

        return await execute_async(
            "propagate_config",
            _op_propagate_config.asyncio_detailed,
            self._namespace, path, version=version,
            client=self._api,
        )

    async def replace_lock(self, path: Any, *, reason: Any = UNSET, expires_at: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``replace_lock``."""

        return await execute_async(
            "replace_lock",
            _op_replace_lock.asyncio_detailed,
            self._namespace, path, reason=reason, expires_at=expires_at, body=body,
            client=self._api,
        )

    async def resolve_draft_config(self, path: Any, *, cast: Any = UNSET, trace_only: Any = UNSET, no_creds: Any = UNSET, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``resolve_draft_config``."""

        return await execute_async(
            "resolve_draft_config",
            _op_resolve_draft_config.asyncio_detailed,
            self._namespace, path, cast=cast, trace_only=trace_only, no_creds=no_creds, content=content, body=body,
            client=self._api,
        )

    async def resolve_parameters(self, path: Any, *, version: Any = UNSET, no_creds: Any = UNSET):
        """OpenAPI operation ``resolve_parameters``."""

        return await execute_async(
            "resolve_parameters",
            _op_resolve_parameters.asyncio_detailed,
            self._namespace, path, version=version, no_creds=no_creds,
            client=self._api,
        )

    async def rotate_resolver_token(self, path: Any, *, token_number: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``rotate_resolver_token``."""

        return await execute_async(
            "rotate_resolver_token",
            _op_rotate_resolver_token.asyncio_detailed,
            self._namespace, path, token_number=token_number, body=body,
            client=self._api,
        )

    async def search_path(self, path: Any, *, q: Any = UNSET, types: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``search_path``."""

        return await execute_async(
            "search_path",
            _op_search_path.asyncio_detailed,
            self._namespace, path, q=q, types=types, limit=limit, offset=offset,
            client=self._api,
        )

    async def search_root(self, *, q: Any = UNSET, types: Any = UNSET, limit: Any = UNSET, offset: Any = UNSET):
        """OpenAPI operation ``search_root``."""

        return await execute_async(
            "search_root",
            _op_search_root.asyncio_detailed,
            self._namespace, q=q, types=types, limit=limit, offset=offset,
            client=self._api,
        )

    async def set_tag(self, path: Any, *, tag: Any = UNSET, version: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``set_tag``."""

        return await execute_async(
            "set_tag",
            _op_set_tag.asyncio_detailed,
            self._namespace, path, tag=tag, version=version, body=body,
            client=self._api,
        )

    async def update_config(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_config``."""

        return await execute_async(
            "update_config",
            _op_update_config.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    async def update_resolver(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_resolver``."""

        return await execute_async(
            "update_resolver",
            _op_update_resolver.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    async def update_secret(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_secret``."""

        return await execute_async(
            "update_secret",
            _op_update_secret.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

    async def update_template(self, path: Any, *, content: Any = UNSET, body: Any = UNSET):
        """OpenAPI operation ``update_template``."""

        return await execute_async(
            "update_template",
            _op_update_template.asyncio_detailed,
            self._namespace, path, content=content, body=body,
            client=self._api,
        )

