_ocmo:
  extend:
    mode: stack
    configs:
      - ../extend/bases/base
  name: stack-{.database.env}.yaml
  render:
    templates:
      - templates/render/extend-fallback.j2@latest
database:
  env: prod
message: from-extend-render
