_ocmo:
  extend:
    mode: align
    by: .patches
    configs:
      - path: ./base-a
        key: .defaults
      - path: ./base-b
        key: .defaults
patches:
  - tier: premium
  - tier: standard
