#!/usr/bin/env python3
"""Build-time generator for the CLI command surface.

Reads sdk/operations.yaml and validates / regenerates commands.yaml.
CI fails when the committed file diverges (coverage gate §5.2).

Usage:
  uv run python scripts/generate_commands.py           # validate only
  uv run python scripts/generate_commands.py --write   # overwrite commands.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SDK_OPS_YAML = REPO_ROOT / "sdk" / "operations.yaml"
CLI_COMMANDS_YAML = REPO_ROOT / "cli" / "commands.yaml"


def load_sdk_operations() -> dict[str, dict]:
    with SDK_OPS_YAML.open() as f:
        data = yaml.safe_load(f) or {}
    return data.get("operations", {})


def load_cli_commands() -> dict[str, dict]:
    with CLI_COMMANDS_YAML.open() as f:
        data = yaml.safe_load(f) or {}
    return data.get("operations", {})


def validate(sdk_ops: dict, cli_ops: dict) -> list[str]:
    """Return list of validation errors."""
    errors: list[str] = []

    # 1. Every operation_id must have a CLI entry
    for op_id in sdk_ops:
        if op_id not in cli_ops:
            errors.append(f"MISSING entry in commands.yaml: {op_id!r}")

    # 2. Every CLI entry must reference a known operation_id
    for op_id in cli_ops:
        if op_id not in sdk_ops:
            errors.append(f"STALE entry in commands.yaml: {op_id!r} (not in operations.yaml)")

    return errors


def generate(sdk_ops: dict, existing_cli_ops: dict) -> dict[str, dict]:
    """Produce a complete commands.yaml operations dict.

    Preserves existing hand_written / skip / confirm overrides.
    """
    result: dict[str, dict] = {}

    for op_id, sdk_cfg in sdk_ops.items():
        # Preserve existing CLI configuration
        existing = existing_cli_ops.get(op_id, {})
        if existing:
            result[op_id] = existing
            continue

        # Infer from SDK cli hints if present
        cli_hint = sdk_cfg.get("cli", {})
        if cli_hint.get("hand_written"):
            result[op_id] = {"hand_written": True}
        elif cli_hint.get("skip"):
            result[op_id] = {"skip": cli_hint["skip"]}
        elif sdk_cfg.get("sdk") is False:
            result[op_id] = {"skip": "Internal SDK operation."}
        else:
            entry: dict = {}
            if cli_hint.get("action"):
                entry["action"] = cli_hint["action"]
            if cli_hint.get("resource"):
                entry["resource"] = cli_hint["resource"]
            if cli_hint.get("confirm"):
                entry["confirm"] = cli_hint["confirm"]
            result[op_id] = entry or {"skip": "Not yet mapped."}

    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="Overwrite commands.yaml with the generated content.")
    args = parser.parse_args()

    sdk_ops = load_sdk_operations()
    cli_ops = load_cli_commands()

    errors = validate(sdk_ops, cli_ops)

    if errors:
        print("Coverage gate failures:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        if not args.write:
            sys.exit(1)

    if args.write:
        generated = generate(sdk_ops, cli_ops)
        with CLI_COMMANDS_YAML.open("w") as f:
            yaml.safe_dump({"operations": generated}, f, default_flow_style=False, sort_keys=False)
        print(f"Wrote {CLI_COMMANDS_YAML}")

        # Also regenerate the static Python map for fast startup
        _write_python_map(generated)


def _write_python_map(operations: dict) -> None:
    """Write ocmo_cli/_commands_map.py from the operations dict."""
    out_path = REPO_ROOT / "cli" / "ocmo_cli" / "_commands_map.py"
    lines = [
        "# AUTO-GENERATED by scripts/generate_commands.py — do not edit.",
        "# Run: uv run python scripts/generate_commands.py --write",
        "",
        "from __future__ import annotations",
        "",
        "OPERATIONS: dict = {",
    ]
    for op_id, cfg in operations.items():
        lines.append(f"    {op_id!r}: {cfg!r},")
    lines.append("}")
    lines.append("")
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")

    if not errors:
        print("Coverage gate: OK")


if __name__ == "__main__":
    main()
