#!/usr/bin/env python3
"""Build-time generator for the CLI command surface.

Reads sdk/operations.yaml and validates / regenerates commands.yaml.
CI fails when the committed file diverges (coverage gate §5.2).

Usage:
  uv run python scripts/generate_commands.py           # validate only
  uv run python scripts/generate_commands.py --write   # overwrite commands.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SDK_OPS_YAML = REPO_ROOT / "sdk" / "operations.yaml"
CLI_COMMANDS_YAML = REPO_ROOT / "cli" / "commands.yaml"


def load_sdk_operations() -> dict[str, dict]:
    with SDK_OPS_YAML.open() as f:
        data = yaml.safe_load(f) or {}
    return data.get("operations", {})


def load_cli_commands() -> dict[str, dict]:
    with CLI_COMMANDS_YAML.open() as f:
        data = yaml.safe_load(f) or {}
    return data.get("operations", {})


def validate(sdk_ops: dict, cli_ops: dict) -> list[str]:
    """Return list of validation errors."""
    errors: list[str] = []

    # 1. Every operation_id must have a CLI entry
    for op_id in sdk_ops:
        if op_id not in cli_ops:
            errors.append(f"MISSING entry in commands.yaml: {op_id!r}")

    # 2. Every CLI entry must reference a known operation_id
    for op_id in cli_ops:
        if op_id not in sdk_ops:
            errors.append(f"STALE entry in commands.yaml: {op_id!r} (not in operations.yaml)")

    return errors


def generate(sdk_ops: dict, existing_cli_ops: dict) -> dict[str, dict]:
    """Produce a complete commands.yaml operations dict.

    Preserves existing hand_written / skip / confirm overrides.
    """
    result: dict[str, dict] = {}

    for op_id, sdk_cfg in sdk_ops.items():
        # Preserve existing CLI configuration
        existing = dict(existing_cli_ops.get(op_id, {}))

        if not existing:
            # Infer from SDK cli hints if present
            cli_hint = sdk_cfg.get("cli", {})
            if cli_hint.get("hand_written"):
                existing = {"hand_written": True}
            elif cli_hint.get("skip"):
                existing = {"skip": cli_hint["skip"]}
            elif sdk_cfg.get("sdk") is False:
                existing = {"skip": "Internal SDK operation."}
            else:
                entry: dict = {}
                if cli_hint.get("action"):
                    entry["action"] = cli_hint["action"]
                if cli_hint.get("resource"):
                    entry["resource"] = cli_hint["resource"]
                if cli_hint.get("confirm"):
                    entry["confirm"] = cli_hint["confirm"]
                existing = entry or {"skip": "Not yet mapped."}

        existing["scope"] = sdk_cfg.get("scope", "namespace")
        result[op_id] = existing

    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Overwrite commands.yaml with the generated content.")
    args = parser.parse_args()

    sdk_ops = load_sdk_operations()
    cli_ops = load_cli_commands()

    errors = validate(sdk_ops, cli_ops)

    if errors:
        print("Coverage gate failures:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        if not args.write:
            sys.exit(1)

    if args.write:
        generated = generate(sdk_ops, cli_ops)
        with CLI_COMMANDS_YAML.open("w") as f:
            yaml.safe_dump({"operations": generated}, f, default_flow_style=False, sort_keys=False)
        print(f"Wrote {CLI_COMMANDS_YAML}")

        # Also regenerate the static Python map for fast startup
        _write_python_map(generated)
        if not errors:
            print("Coverage gate: OK")


def _write_python_map(operations: dict) -> None:
    """Write ocmo_cli/_commands_map.py from the operations dict."""
    import pprint

    out_path = REPO_ROOT / "cli" / "ocmo_cli" / "_commands_map.py"
    header = "\n".join(
        [
            "# AUTO-GENERATED by scripts/generate_commands.py — do not edit.",
            "# Run: uv run python scripts/generate_commands.py --write",
            "",
            "from __future__ import annotations",
            "",
            "OPERATIONS: dict = ",
        ]
    )
    body = pprint.pformat(operations, width=118, sort_dicts=False)
    out_path.write_text(f"{header}{body}\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
