"""
Django settings for ocmoapi project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from typing import Any

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Helper functions
def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip('"').strip("'").lower() in ("true", "1", "yes")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
#
# Defaults below (SECRET_KEY, DEBUG=True, database password) are for local dev only.
# Production: set DJANGO_SECRET_KEY, DJANGO_DEBUG=False, POSTGRES_PASSWORD, OCMO_MASTER_KEY,
# and OIDC_* via environment. See ../.env.example and docs/quickstart/configuration.md.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-0=&n7jf-=15k@uotre7%8x$2c7s#vf-w^z$5)@b&2qe2&=b@6p")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "ninja",
    "core",  # For models discovery
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.ResolveCacheHeaderMiddleware",
]

ROOT_URLCONF = "ocmoapi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "ocmoapi/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "ocmoapi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "ocmoapi"),
        "USER": os.environ.get("POSTGRES_USER", "ocmoapi-user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "ocmoapi1906031218435"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict[str, Any]] = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "config_api": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
        },
        "rq.worker": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}


# API Configuration
API_VERSION = "v1"
API_TITLE = "Open Configuration Management API"
API_DESCRIPTION = "Multi-tenant configuration management with versioning and access control"

SECURE_CROSS_ORIGIN_OPENER_POLICY = None  # Should be "same-origin-allow-popups" for prod

TESTING = "test" in sys.argv
OIDC_DISCOVERY_DOCUMENT_URL = os.environ.get(
    "OIDC_DISCOVERY_DOCUMENT_URL", "http://oidc-provider:9000/dex/.well-known/openid-configuration"
)
OIDC_JWKS_URL = os.environ.get("OIDC_JWKS_URL", "http://oidc-provider:9000/dex/keys")
# Dex includes a trailing slash in JWT `iss`; keep settings aligned for validation and SPA OIDC.
OIDC_ISSUER = f"{os.environ.get('OIDC_ISSUER', 'http://localhost:8080/dex').rstrip('/')}/"
# Browser-facing OAuth endpoints (Swagger, CLI). Server-side JWKS/discovery may use internal URLs above.
_oidc_issuer_base = OIDC_ISSUER.rstrip("/")
OIDC_AUTHORIZATION_URL = os.environ.get("OIDC_AUTHORIZATION_URL", f"{_oidc_issuer_base}/auth")
OIDC_TOKEN_URL = os.environ.get("OIDC_TOKEN_URL", f"{_oidc_issuer_base}/token")
OIDC_SWAGGER_REDIRECT_URL = os.environ.get(
    "OIDC_SWAGGER_REDIRECT_URL",
    "http://localhost:8080/api/docs/oauth2-redirect.html",
)
OIDC_CLIENT_ID = os.environ.get("OIDC_CLIENT_ID", "ocmo-api")
# JWT `aud` values accepted by the API. Browser tokens use ocmo-api; SDK/CLI service
# tokens minted for the ocmo-sdk confidential client use ocmo-sdk.
OIDC_JWT_AUDIENCES = [
    audience.strip()
    for audience in os.environ.get("OIDC_JWT_AUDIENCES", f"{OIDC_CLIENT_ID},ocmo-sdk").split(",")
    if audience.strip()
]
OIDC_SCOPES = os.environ.get("OIDC_SCOPES", "openid profile email groups")
# JWT claims used to map OIDC token fields to OCMO user identity (configure per IdP).
OIDC_USER_ID_CLAIM = os.environ.get("OIDC_USER_ID_CLAIM", "sub")
OIDC_USER_EMAIL_CLAIM = os.environ.get("OIDC_USER_EMAIL_CLAIM", "email")
OIDC_USER_DISPLAY_NAME_CLAIM = os.environ.get("OIDC_USER_DISPLAY_NAME_CLAIM", "name")
# JWT claim used to identify global administrators (e.g. "groups")
OIDC_GLOBAL_ADMIN_CLAIM = os.environ.get("OIDC_GLOBAL_ADMIN_CLAIM", "email")
# Expected value of that claim for global administrators (exact match)
OIDC_GLOBAL_ADMIN_VALUE = os.environ.get("OIDC_GLOBAL_ADMIN_VALUE", "admin@example.com")

OCMO_CONFIG_METADATA_KEY = "_ocmo"
# Public base URL for absolute links in API responses (e.g. signed resolve download URLs).
# When set, overrides request-derived host/port (needed behind reverse proxies).
OCMO_PUBLIC_URL = os.environ.get("OCMO_PUBLIC_URL", "").rstrip("/")
# Audit verbosity: "resolve" (default), "modifications-and-resolve", or "all".
# Audit cannot be fully disabled; invalid values fall back to "resolve".
# Local DEBUG deployments default to "all" so reads and writes are audited.
OCMO_AUDIT_MODE = os.environ.get(
    "OCMO_AUDIT_MODE",
    "all" if DEBUG else "resolve",
)
# Per-process LRU cap for compiled permission policy sets and global rules.
OCMO_PERMISSIONS_CACHE_SIZE = int(os.environ.get("OCMO_PERMISSIONS_CACHE_SIZE", "1024"))
OCMO_MAX_CONFIG_RESOLVE_DEPTH = int(os.environ.get("OCMO_MAX_CONFIG_RESOLVE_DEPTH", "20"))
OCMO_MAX_EXTEND_CONFIGS = int(os.environ.get("OCMO_MAX_EXTEND_CONFIGS", "50"))
OCMO_MAX_RENDER_TEMPLATES = int(os.environ.get("OCMO_MAX_RENDER_TEMPLATES", "50"))
OCMO_MAX_CONFIG_PARAMETERS = int(os.environ.get("OCMO_MAX_CONFIG_PARAMETERS", "50"))
OCMO_MAX_PARAMETER_TRANSFORMERS = int(os.environ.get("OCMO_MAX_PARAMETER_TRANSFORMERS", "10"))
OCMO_MAX_PROPAGATION_TARGETS = int(os.environ.get("OCMO_MAX_PROPAGATION_TARGETS", "5"))
OCMO_WEBHOOKS_CACHE_SIZE = int(os.environ.get("OCMO_WEBHOOKS_CACHE_SIZE", "256"))
OCMO_WEBHOOK_TIMEOUT_SECONDS = float(os.environ.get("OCMO_WEBHOOK_TIMEOUT_SECONDS", "5"))

# Secrets encryption — base64-encoded 32-byte AES-256 master key (KEK).
# Application refuses to start if this is absent when secrets are used.
_TEST_MASTER_KEY = "ZDPuvW6Hx/1UxDK7K/CydLouVKtJl24nbHyb2EkvTzs="
OCMO_MASTER_KEY = os.environ.get("OCMO_MASTER_KEY") or (_TEST_MASTER_KEY if TESTING else "")

# Resolve artifact storage.
OCMO_RESOLVE_ARTIFACT_BACKEND = os.environ.get("OCMO_RESOLVE_ARTIFACT_BACKEND", "fs")
OCMO_RESOLVE_ARTIFACT_DIR = os.environ.get("OCMO_RESOLVE_ARTIFACT_DIR", "/tmp/ocmo/resolved")
OCMO_RESOLVE_URL_TTL = int(os.environ.get("OCMO_RESOLVE_URL_TTL", "300"))
OCMO_RESOLVE_ARTIFACT_MAX_AGE = int(os.environ.get("OCMO_RESOLVE_ARTIFACT_MAX_AGE", "86400"))
# Minimum seconds between fs artifact sweeps on the resolve path (per worker process).
OCMO_RESOLVE_ARTIFACT_SWEEP_INTERVAL = int(os.environ.get("OCMO_RESOLVE_ARTIFACT_SWEEP_INTERVAL", "900"))
# X-Accel-Redirect Nginx location prefix. When empty, the API serves bytes directly (dev mode).
OCMO_RESOLVE_DOWNLOAD_XACCEL_LOCATION = os.environ.get("OCMO_RESOLVE_DOWNLOAD_XACCEL_LOCATION", "")

_redis_host = os.environ.get("REDIS_HOST", "localhost")
_redis_port = os.environ.get("REDIS_PORT", "6379")
_redis_db = os.environ.get("REDIS_DB", "0")

# Redis artifact backend settings (used when OCMO_RESOLVE_ARTIFACT_BACKEND=redis).
# Defaults to REDIS_HOST/PORT/DB env vars when not set explicitly.
OCMO_RESOLVE_ARTIFACT_REDIS_URL = os.environ.get(
    "OCMO_RESOLVE_ARTIFACT_REDIS_URL",
    f"redis://{_redis_host}:{_redis_port}/{_redis_db}",
)
OCMO_RESOLVE_ARTIFACT_REDIS_GZIP = os.environ.get("OCMO_RESOLVE_ARTIFACT_REDIS_GZIP", "false").lower() == "true"

# Short-circuit resolve cache.
# OCMO_RESOLVE_CACHE_BACKEND: "locmem" (default, dev/test) or "redis" (production).
OCMO_RESOLVE_CACHE_BACKEND = os.environ.get("OCMO_RESOLVE_CACHE_BACKEND", "locmem")
OCMO_RESOLVE_CACHE_TTL = int(os.environ.get("OCMO_RESOLVE_CACHE_TTL", "3600"))

_resolve_cache_redis_url = os.environ.get(
    "OCMO_RESOLVE_CACHE_REDIS_URL",
    f"redis://{_redis_host}:{_redis_port}/{_redis_db}",
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "resolve": (
        {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _resolve_cache_redis_url,
        }
        if OCMO_RESOLVE_CACHE_BACKEND == "redis"
        else {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "resolve-cache",
        }
    ),
}

# Upload size limits (bytes)
OCMO_MAX_CONFIG_UPLOAD_BYTES = int(os.environ.get("OCMO_MAX_CONFIG_UPLOAD_BYTES", str(1 * 1024 * 1024)))  # 1 MiB
OCMO_MAX_TEMPLATE_UPLOAD_BYTES = int(os.environ.get("OCMO_MAX_TEMPLATE_UPLOAD_BYTES", str(1 * 1024 * 1024)))
OCMO_MAX_SECRET_UPLOAD_BYTES = int(os.environ.get("OCMO_MAX_SECRET_UPLOAD_BYTES", str(256 * 1024)))  # 256 KiB
