_ocmo:
  parameters:
    db_password:
      type: secret
      value: ./creds/db:password
      description: db password
  cast:
    format: json

connection:
  password: "{!db_password}"
  user: dbuser
