# Generated by Django 6.0.2 on 2026-02-14 10:35

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="TreeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=4096)),
                ("description", models.TextField(max_length=4096)),
                ("node_type", models.CharField(max_length=255)),
                ("author", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.treeitem",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=4096)),
                ("permissions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "treeitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.treeitem",
                    ),
                ),
                ("tags", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.treeitem",),
        ),
        migrations.CreateModel(
            name="Resolver",
            fields=[
                (
                    "treeitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.treeitem",
                    ),
                ),
                ("token1", models.CharField(blank=True, max_length=64, null=True)),
                ("token1_last_used", models.DateTimeField(blank=True, null=True)),
                ("token2", models.CharField(blank=True, max_length=64, null=True)),
                ("token2_last_used", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.treeitem",),
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "treeitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.treeitem",
                    ),
                ),
                ("tags", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.treeitem",),
        ),
        migrations.AddField(
            model_name="treeitem",
            name="namespace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tree",
                to="core.namespace",
            ),
        ),
        migrations.AddIndex(
            model_name="treeitem",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["namespace", "path"],
                name="treeitem_path_gist_idx",
                opclasses=["gist_int8_ops", "gist_text_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="treeitem",
            unique_together={("namespace", "path")},
        ),
    ]
