# Generated by Django 6.0.2 on 2026-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
