# Generated by Django 6.0.2 on 2026-02-15 21:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_namespace_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="namespace",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="core_namespace_unique_name_case_insensitive",
            ),
        ),
    ]
