# Generated by Django 6.0.2 on 2026-02-15 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_namespace_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField()),
                ("data", models.TextField()),
                ("updater", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.config",
                    ),
                ),
            ],
            options={
                "ordering": ["config", "version"],
                "indexes": [
                    models.Index(
                        fields=["config", "version"],
                        name="core_config_config__63e21d_idx",
                    )
                ],
                "unique_together": {("config", "version")},
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField()),
                ("data", models.TextField()),
                ("updater", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.template",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "version"],
                "indexes": [
                    models.Index(
                        fields=["template", "version"],
                        name="core_templa_templat_a7602f_idx",
                    )
                ],
                "unique_together": {("template", "version")},
            },
        ),
    ]
