# Generated by Django 6.0.2 on 2026-02-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_configversion_templateversion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templateversion",
            options={"ordering": ["config", "version"]},
        ),
        migrations.RemoveIndex(
            model_name="templateversion",
            name="core_templa_templat_a7602f_idx",
        ),
        migrations.RenameField(
            model_name="templateversion",
            old_name="template",
            new_name="config",
        ),
        migrations.AlterUniqueTogether(
            name="templateversion",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="configversion",
            name="version",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="templateversion",
            name="version",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="templateversion",
            unique_together={("config", "version")},
        ),
        migrations.AddIndex(
            model_name="templateversion",
            index=models.Index(fields=["config", "version"], name="core_templa_config__47ac69_idx"),
        ),
    ]
