# Generated by Django 6.0.2 on 2026-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_templateversion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configversion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templateversion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
