# Generated by Django 6.0.2 on 2026-05-23 17:10

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_configversion_deleted_at_templateversion_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalPermissionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.FloatField(db_index=True)),
                ("rule", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "treeitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.treeitem",
                    ),
                ),
                ("tags", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.treeitem",),
        ),
        migrations.RemoveField(
            model_name="namespace",
            name="permissions",
        ),
        migrations.AddField(
            model_name="namespace",
            name="encrypted_dek",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="namespace",
            name="git_sync_tag",
            field=models.CharField(default="latest", max_length=50),
        ),
        migrations.AddField(
            model_name="namespace",
            name="permissions_tag",
            field=models.CharField(default="latest", max_length=50),
        ),
        migrations.AddField(
            model_name="namespace",
            name="webhooks_tag",
            field=models.CharField(default="latest", max_length=50),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="description",
            field=models.TextField(default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_-]+$",
                        "Only alphanumeric characters, hyphens and underscores are allowed.",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="SecretVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(editable=False)),
                ("encrypted_data", models.BinaryField(blank=True, null=True)),
                ("updater", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.secret",
                    ),
                ),
            ],
            options={
                "ordering": ["secret", "version"],
                "indexes": [
                    models.Index(
                        fields=["secret", "version"],
                        name="core_secret_secret__086a75_idx",
                    )
                ],
                "unique_together": {("secret", "version")},
            },
        ),
    ]
