# Generated by Django 6.0.2 on 2026-06-26 20:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_resolver_token_encryption"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("client_ip", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("auth_id", models.CharField(max_length=512)),
                ("auth_email", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("user", "user"), ("resolver", "resolver")],
                        max_length=16,
                    ),
                ),
                (
                    "token_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("http_method", models.CharField(max_length=16)),
                ("api_endpoint", models.CharField(max_length=2048)),
                (
                    "object_type",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "object_path",
                    models.CharField(blank=True, db_index=True, max_length=2048, null=True),
                ),
                ("object_version", models.PositiveIntegerField(blank=True, null=True)),
                ("permission_ok", models.BooleanField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "resolve_type",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "direct"), ("nested", "nested")],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
                ("from_cache", models.BooleanField(blank=True, null=True)),
                (
                    "event_kind",
                    models.CharField(
                        choices=[
                            ("operation", "operation"),
                            ("resolve_request", "resolve_request"),
                            ("resolve_participant", "resolve_participant"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.RenameIndex(
            model_name="treelock",
            new_name="core_treelo_namespa_5be922_idx",
            old_name="core_treel_namespace_path_idx",
        ),
        migrations.RenameIndex(
            model_name="treelock",
            new_name="core_treelo_namespa_b73013_idx",
            old_name="core_treel_namespace_expires_idx",
        ),
        migrations.AddField(
            model_name="auditevent",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="core.namespace",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants",
                to="core.auditevent",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["namespace", "occurred_at"],
                name="core_audite_namespa_71ba20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["object_path", "resolve_type", "occurred_at"],
                name="core_audite_object__277b76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["auth_id"], name="core_audite_auth_id_5d6b81_idx"),
        ),
    ]
