# Generated by Django 6.0.2 on 2026-06-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_audit_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="namespace_name",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["namespace_name", "occurred_at"],
                name="core_audite_namespa_f7b50d_idx",
            ),
        ),
    ]
