# Generated by Django 6.0.2 on 2026-06-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_audit_event_namespace_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditevent",
            name="core_audite_object__277b76_idx",
        ),
        migrations.RenameField(
            model_name="auditevent",
            old_name="object_path",
            new_name="object_id",
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["object_id", "resolve_type", "occurred_at"],
                name="core_audite_object__03ac1a_idx",
            ),
        ),
    ]
